In [1]:
import pandas as pd
PATH = "~/data/movies/dailyboxoffice/dt=20240101"
df = pd.read_parquet(PATH)
len(df)

50

In [8]:
df_grouped_nm = df.groupby(['movieNm', 'multiMovieYn', 'repNationCd'], dropna=False, observed=False) \
                  .size() \
                  .reset_index(name='count')

group = df_grouped_nm

print(df_grouped_nm)

       movieNm multiMovieYn repNationCd  count
0       3일의 휴가            N           F      0
1       3일의 휴가            N           K      0
2       3일의 휴가            N         NaN      1
3       3일의 휴가            Y           F      0
4       3일의 휴가            Y           K      0
..         ...          ...         ...    ...
220  피아니스트의 전설            Y           K      0
221  피아니스트의 전설            Y         NaN      1
222  피아니스트의 전설          NaN           F      0
223  피아니스트의 전설          NaN           K      0
224  피아니스트의 전설          NaN         NaN      0

[225 rows x 4 columns]

In [9]:
def get_counts(group): # 인자 이름을 group으로 변경 (더 명확하게 그룹 데이터임을 나타냄)
    counts = pd.Series({
        'multiMovieYn=Y': group[group['multiMovieYn'] == 'Y']['count'].sum() if 'count' in group.columns and 'multiMovieYn' in group.columns else 0,
        'multiMovieYn=N': group[group['multiMovieYn'] == 'N']['count'].sum() if 'count' in group.columns and 'multiMovieYn' in group.columns else 0,
        'repNationCd=K': group[group['repNationCd'] == 'K']['count'].sum() if 'count' in group.columns and 'repNationCd' in group.columns else 0,
        'repNationCd=F': group[group['repNationCd'] == 'F']['count'].sum() if 'count' in group.columns and 'repNationCd' in group.columns else 0
    })
    return counts

In [11]:
# 각 movieNm별 count 적용 및 결과 병합
result_df = group.apply(get_counts).reset_index()

print(result_df)

AttributeError: 'Series' object has no attribute 'columns'

In [21]:
import pandas as pd

PATH = "~/data/movies/dailyboxoffice/dt=20240101"
df = pd.read_parquet(PATH)
len(df)

50

In [22]:
df_grouped_nm = df.groupby(['movieNm', 'multiMovieYn', 'repNationCd'], dropna=False, observed=False) \
                    .size() \
                    .reset_index(name='count')
print(df_grouped_nm)

       movieNm multiMovieYn repNationCd  count
0       3일의 휴가            N           F      0
1       3일의 휴가            N           K      0
2       3일의 휴가            N         NaN      1
3       3일의 휴가            Y           F      0
4       3일의 휴가            Y           K      0
..         ...          ...         ...    ...
220  피아니스트의 전설            Y           K      0
221  피아니스트의 전설            Y         NaN      1
222  피아니스트의 전설          NaN           F      0
223  피아니스트의 전설          NaN           K      0
224  피아니스트의 전설          NaN         NaN      0

[225 rows x 4 columns]

In [23]:
def get_counts(group):
    counts = pd.Series({
        'multiMovieYn=Y': group[group['multiMovieYn'] == 'Y']['count'].sum() if 'count' in group.columns and 'multiMovieYn' in group.columns else 0,
        'multiMovieYn=N': group[group['multiMovieYn'] == 'N']['count'].sum() if 'count' in group.columns and 'multiMovieYn' in group.columns else 0,
        'repNationCd=K': group[group['repNationCd'] == 'K']['count'].sum() if 'count' in group.columns and 'repNationCd' in group.columns else 0,
        'repNationCd=F': group[group['repNationCd'] == 'F']['count'].sum() if 'count' in group.columns and 'repNationCd' in group.columns else 0
    })
    return counts

In [24]:
# 각 movieNm별 count 적용 및 결과 병합
result_df = df_grouped_nm.groupby('movieNm', group_keys=False).apply(get_counts, include_groups=False).reset_index()

print(result_df)

                                 movieNm  multiMovieYn=Y  multiMovieYn=N  \
0                                 3일의 휴가               0               1
1                                     괴물               1               0
2                              교토에서 온 편지               0               0
3                         그대들은 어떻게 살 것인가               1               0
4                                   나폴레옹               0               1
5                                   너와 나               0               0
6                             노량: 죽음의 바다               0               1
7                              도티와 영원의 탑               0               1
8                          류이치 사카모토: 오퍼스               1               0
9                              리빙: 어떤 인생               1               0
10                                립세의 사계               1               0
11                             말하고 싶은 비밀               0               1
12  바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!               1               0
13                      뽀로로 극장판 슈퍼스타 대모험               0               1
14                            사랑은 낙엽을 타고               1               0
15                                 서울의 봄               0               1
16  신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~               0               1
17                               싱글 인 서울               0               0
18                          아쿠아맨과 로스트 킹덤               0               1
19                                어른 김장하               0               0
20                엔시티 네이션 : 투 더 월드 인 시네마               0               0
21                                  쿼바디스               1               0
22                                  크레센도               1               0
23                            트롤: 밴드 투게더               0               1
24                             피아니스트의 전설               1               0

    repNationCd=K  repNationCd=F
0               1              0
1               0              1
2               1              0
3               0              0
4               0              0
5               1              0
6               1              0
7               1              0
8               0              1
9               0              1
10              0              0
11              0              1
12              0              1
13              1              0
14              0              1
15              1              0
16              0              1
17              1              0
18              0              1
19              1              0
20              1              0
21              0              0
22              0              1
23              0              1
24              0              0

In [25]:
result_df

,movieNm,multiMovieYn=Y,multiMovieYn=N,repNationCd=K,repNationCd=F
0,3일의 휴가,0,1,1,0
1,괴물,1,0,0,1
2,교토에서 온 편지,0,0,1,0
3,그대들은 어떻게 살 것인가,1,0,0,0
4,나폴레옹,0,1,0,0
5,너와 나,0,0,1,0
6,노량: 죽음의 바다,0,1,1,0
7,도티와 영원의 탑,0,1,1,0
8,류이치 사카모토: 오퍼스,1,0,0,1
9,리빙: 어떤 인생,1,0,0,1
10,립세의 사계,1,0,0,0
11,말하고 싶은 비밀,0,1,0,1
12,"바다 탐험대 옥토넛 어보브 앤 비욘드: 버드, 옥토경보를 울려라!",1,0,0,1
13,뽀로로 극장판 슈퍼스타 대모험,0,1,1,0
14,사랑은 낙엽을 타고,1,0,0,1
15,서울의 봄,0,1,1,0
16,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,0,1,0,1
17,싱글 인 서울,0,0,1,0
18,아쿠아맨과 로스트 킹덤,0,1,0,1
19,어른 김장하,0,0,1,0
20,엔시티 네이션 : 투 더 월드 인 시네마,0,0,1,0
21,쿼바디스,1,0,0,0
22,크레센도,1,0,0,1
23,트롤: 밴드 투게더,0,1,0,1
24,피아니스트의 전설,1,0,0,0

In [28]:
import pandas as pd

PATH = "~/data/movies/dailyboxoffice/dt=20240101"
df = pd.read_parquet(PATH)

# multiMovieYn, repNationCd과 추가로 movieNm를 group (movieNm는 추후 고유 키값으로 활용됨)
df_grouped_nm = df.groupby(['movieNm', 'multiMovieYn', 'repNationCd'], dropna=False, observed=False) \
                  .size() \
                  .reset_index(name='count')

# multiMovieYn, repNationCd 값별 count를 조건에 맞게 sumif
def get_counts(group):
    counts = pd.Series({
        'multiMovieYn=Y': group[group['multiMovieYn'] == 'Y']['count'].sum() if 'count' in group.columns and 'multiMovieYn' in group.columns else 0,
        'multiMovieYn=N': group[group['multiMovieYn'] == 'N']['count'].sum() if 'count' in group.columns and 'multiMovieYn' in group.columns else 0,
        'repNationCd=K': group[group['repNationCd'] == 'K']['count'].sum() if 'count' in group.columns and 'repNationCd' in group.columns else 0,
        'repNationCd=F': group[group['repNationCd'] == 'F']['count'].sum() if 'count' in group.columns and 'repNationCd' in group.columns else 0
    })
    return counts

# 각 movieNm별 count 적용 및 결과 병합
result_df = df_grouped_nm.groupby('movieNm', group_keys=False).apply(get_counts, include_groups=False).reset_index()

result_df #jupyter lab 
print(result_df) # print